### ISSUE TITLE
Videos get downloaded, but never uploaded + No/Incorrect Handling for 2FA

### ISSUE THREAD

**Issue by TheOfficialTAGM** [sujay1599/InstagramTheftyScraperPosterHuman#12]
1st Issue: I've attached a screenshot for better understanding, basically, the videos download fine, but when it comes to uploading - its on a what seems to be a loop which results in nothing actually being uploaded
![image](https://github.com/user-attachments/assets/6b11d372-374e-4fcf-9f48-f93b4a95b98f)

2nd: Incorrect handling for 2FA. 2FA, for Authenticator Apps and/or Email codes isn't handled properly here. When logging into any account with 2FA, it results in this error despite everything being clean - instead of asking for 2FA Code. "Failed to login using username and password: The password you entered is incorrect. Please try again. If you are sure that the password is correct, then change your IP address, because it is added to the blacklist of the Instagram 
Server"

**Comment by sujay1599** [comment]
First download the newest version. 

delete your session file for said accounts. 

Log into IG on ur phone -> forgot password -> reset password (shows IG u have possession of the account) 

Start program for start_config.py


2FA is not implemented; if people require it I can add it. 

Lmk if that helps!

**Comment by sujay1599** [comment]
Also currently public request are broken - https://github.com/subzeroid/instagrapi/pull/1844#issuecomment-2018947707

So I'm working on a V3.01

**Comment by TheOfficialTAGM** [comment]
added you on discord!

**Comment by sujay1599** [comment]
Thanks for sharing I will work on getting it incorporated. 

So login happens in config_setup.py to create the initial file. 

Main.py calls auth.py to see if sesssion is valid, if valid inject cookie, updates time. 


For 2fa it will the first question asked when running. 

Sujay
