### ISSUE TITLE
Blocked IP issue

### ISSUE THREAD

**Issue by 2077DevWave** [sujay1599/InstagramTheftyScraperPosterHuman#20]
is there any way to fix :
"We can send you an email to help you get back into your account. If you are sure that the password is correct, then change your IP address, because it is added to the blacklist of the Instagram Server"

i test some server but program still show this :/

**Comment by sujay1599** [comment]
Yes, so in this case to resolve that problem, in the meantime, I would delete .json file for that account. 

I have a fix in mind which when an air similar to that pops up, it will delete the account file and the three status files plus the key. 



Add me as a friend on Discord! Invite expires in 1 week: https://discord.gg/xT5fVVkd
