### ISSUE TITLE
it stop scrapping after some time 6-7 hour and restarting runs below 2 lines in loop

### ISSUE THREAD

**Issue by iamjpsharma** [sujay1599/InstagramTheftyScraperPosterHuman#25]
Found 0 unuploaded reels
No new reels to upload. Restarting scraping...

**Comment by sujay1599** [comment]
What's the YAML look like?

**Comment by iamjpsharma** [comment]
Attempting call 1/5
Loaded existing status file.
Updated status file.
Attempting call 1/5
Loaded existing status file.
Updated status file.
Attempting call 1/5
Loaded existing status file.
Updated status file.
Attempting call 1/5
Loaded existing status file.
Updated status file.
Attempting call 1/5
Loaded existing status file.
Updated status file.
Attempting call 1/5
Loaded existing status file.
Updated status file.
Attempting call 1/5
Loaded existing status file.
Updated status file.
Attempting call 1/5
Loaded existing status file.
Updated status file.
Attempting call 1/5

this goes in running continueously

**Comment by iamjpsharma** [comment]
custom_tags:
- 1min
- LongerVideos
- swifttok
- FallGuysMoments
- MakeupInspo
- PaTiChallenge
- ForYourPride
- ohno
- anime
- FilmTok
- Fashionista
- ShoppingTherapy
- BeautyDay
- SportsPhotography
- EntertainmentNews
- GreenEnergy
- EcoFriendly
- MentalHealthMatters
- DigitalArt
- TravelGoals
deleting:
  delete_interval_minutes: 5
description:
  credit:
    give_credit: true
  hashtags:
    use_hashtags: false
  use_original: true
instagram: 
  password: hashcode
  username: hashcode
key: hash
leave_comment: false
proxy: ''
scraping:
  enabled: true
  like_reels: false
  num_reels: 3
  profiles: list of accounts
  scrape_interval_minutes: 10
uploading:
  add_to_story: true
  enabled: true
  upload_interval_minutes: 20

**Comment by sujay1599** [comment]
Okay so scrapping happens first. 

Set it to scrape 3 videos from x profiles 480 

Keeep deletion time 9000

That will resolve 

Let me get on my laptop

**Comment by sujay1599** [comment]
Logic is config > main > scrape > upload > delete > repeat.

**Comment by iamjpsharma** [comment]
yes scrapping happens first. delete not working a lot of videos in download folder

**Comment by sujay1599** [comment]
yeh delete fx needs work no time to fix but it accomplishes for the day and can run multiple accounts. 

ex:
custom_tags:
- 1min
- LongerVideos
- swifttok
- FallGuysMoments
- MakeupInspo
- PaTiChallenge
- ForYourPride
- ohno
- anime
- FilmTok
- Fashionista
- ShoppingTherapy
- BeautyDay
- SportsPhotography
- EntertainmentNews
- GreenEnergy
- EcoFriendly
- MentalHealthMatters
- DigitalArt
- TravelGoals
- SeptemberVibes
- SeptemberFeels
- AutumnChuckles
- SeptemberMemories
- AutumnVibes
- ComicalAutumn
- FallFunnies
- SeptemberGiggles
- LaughingThroughFall
- FallHumor
- NYFW
- BackInTheDay
- DiaDeLosMuertos
- WinterOutfit
- SummerOfGaming
- Over50Fashion
- SustainableBeauty
- WeddingIdeas
- Camping
- SummerMakeup
- Thrifting
- VintageFashion
deleting:
  delete_interval_minutes: 90000
description:
  credit:
    give_credit: false
  custom_description: ''
  hashtags:
    use_hashtags: false
  use_original: false
instagram:
  password: gAAAAABm-UulgjhpYx6P3NfWm_OTcqoict1HQk2f-7Wg8q61WaFkcfVNoJTLoRrTUghhFyjWyQFd6cDqMKvs--
  username: gAAAAA
key: KEY
leave_comment: false
proxy: ''
scraping:
  enabled: true
  like_reels: false
  num_reels: 3
  profiles: laxative sigma.shitpostin money_crown_1
  scrape_interval_minutes: 6000
uploading:
  add_to_story: false
  enabled: false
  upload_interval_minutes: 24

**Comment by iamjpsharma** [comment]
Will delete those files but this issues raise after certain hours like 6-7 hours. Loop goes on continuously then i do git clone again in different folder and setup again

**Comment by sujay1599** [comment]
Hmmm I might just be more versed but what's the freq of scraping and posting. 

I scrape all videos I will post in 24 hours and upload every 33 mins. 

I will look into it.

**Comment by sujay1599** [comment]
![1 loop completion than error](https://github.com/user-attachments/assets/c1db1c82-c9ef-41b3-8f85-ccc2fe1d7ae4)
This is a loop it completed! 


it works but the timing; aim to have it be able to run autonomously

**Comment by iamjpsharma** [comment]
yeah... i think.... for me if all scrapped video are uploaded then this loop runs

**Comment by iamjpsharma** [comment]
and there are no new videos to scrap on profile?

**Comment by iamjpsharma** [comment]
if we stop after above loop and then run then below loop goes in 

Found 0 unuploaded reels
No new reels to upload. Restarting scraping...
Found 0 unuploaded reels
No new reels to upload. Restarting scraping...
Found 0 unuploaded reels
No new reels to upload. Restarting scraping...
Found 0 unuploaded reels
No new reels to upload. Restarting scraping...
Found 0 unuploaded reels
No new reels to upload. Restarting scraping...
and so on------

**Comment by sujay1599** [comment]
Friend,

Delete the the session for said.  It has gone bad you need cookie.

**Comment by sujay1599** [comment]
Lmk if that works.

**Comment by iamjpsharma** [comment]
I do it every time and then it start working and after 6-7 hr it do same also i got logged out of my devices and got warnings for suspicious activity detected

**Comment by sujay1599** [comment]
hmmm I think it needs an error handle agent  


the red text comes waiting for her acknowledged that there has been breach for detection [bot activity] 


rotate out the tags and the tek defaults 

use a LLM to make it happen quickly

open to ideas

**Comment by iamjpsharma** [comment]
can't we make it random ? like tags, profiles like out of 10 just scrap 3 profile then post then scrap another 3 like that right now it scraps then post thats it. scraping 2nd time not works for me. i need to setup again then

**Comment by iamjpsharma** [comment]
Attempting call 1/5
Error on attempt 1/5
Error message: login_required
Rate limit or login required. Retrying in 1 seconds...
Re-logging in after attempt 1
Re-login failed: Unknown ({}). Attempting fresh login...
Logged in using existing session file
Attempting call 2/5
Error on attempt 2/5
Error message: login_required
Rate limit or login required. Retrying in 2 seconds...
Re-logging in after attempt 2
Re-login failed: Unknown ({}). Attempting fresh login...
Logged in using existing session file
Attempting call 3/5
Error on attempt 3/5
Error message: login_required
Rate limit or login required. Retrying in 4 seconds...
Re-logging in after attempt 3
Re-login failed: Unknown ({}). Attempting fresh login...
Logged in using existing session file
Attempting call 4/5

**Comment by sujay1599** [comment]
You change the password. Logout all sessions from IG app?

Only the loop works for me but you must calculate the timing properly. 


If seeking  bot which searches for tags u could use mine as a base???

I'll c what I can do.

**Comment by iamjpsharma** [comment]
I did not change the password on my Instagram account, but when I started scraping videos, Instagram detected the automated behavior and logged me out of all my devices. After I logged back in, I got a popup warning that automated behavior was suspected. However, once the scraping was done and I started uploading videos, Instagram didn't detect any suspicious activity and all uploads were successful.

**Comment by sujay1599** [comment]
It's not a marathon u can't upload videos every 10 mins. 

That doesn't work. 

Scrape like 24 videos for the day. 

And upload at 35 min intervals with default titles or custom titles. 

Make sense? 


Don't log into that account either once password is changed.

**Comment by iamjpsharma** [comment]
Yes my upload time is 59 mins but uploading is no issue scrapping detects
and logout from all places

**Comment by sujay1599** [comment]
will be pushing update soon

I see the issue now

interm delete the key, json, and start from start; assure you type true and false in the config_setup.py vs t/f.

**Comment by sujay1599** [comment]
should be good now!
