### ISSUE TITLE
Uuid when changing users

### ISSUE THREAD

**Issue by sujay1599** [sujay1599/InstagramTheftyScraperPosterHuman#5]
Working on compiling different uuid and session. 

If user a logs in it will assign said uuid setting always and refresh. 

If user b will assign user b. 

This will reduce flagging. 

Solution is to create a database 

Name:session.json and call it if username is in db, If not normal login and add to db.

**Comment by iekamjotsingh** [comment]
You're the gawd bro, Whats your linkedin?

**Comment by sujay1599** [comment]
send me msg

**Comment by sujay1599** [comment]
/sujayamin/

send request!

**Comment by sujay1599** [comment]
Issue resolved; saving encrypted sessions keys
