### ISSUE TITLE
upload_log.txt not found.

### ISSUE THREAD

**Issue by kepler22bintusiast** [sujay1599/InstagramTheftyScraperPosterHuman#7]
Any solutions?
![Screenshot 2024-08-04](https://github.com/user-attachments/assets/0bd84381-eaf1-4702-8c4d-d09a632ec4c4)

**Comment by sujay1599** [comment]
Try starting from config.py

It seems not creating that file. 

You can make a blank version; that txt file just keeps the log of which videos were uploaded. 

Hope this helps. I'll be pushing updates soon.

**Comment by sujay1599** [comment]
try new version

**Comment by kepler22bintusiast** [comment]
Tried the new updates. Unfortunately the update log problem persists even when I'm manually creating the log txt. Really like the idea and simplicity of this project tho. Looking forward to your next updates!

**Comment by sujay1599** [comment]
Can you show the problem?!

**Comment by kepler22bintusiast** [comment]
The following screenshots were taken after manually creating upload_log.txt. You can see in the screenshot above what happens if the .txt file is not created manually.
The release date shown on the dashboard screenshot is incorrect; I am using the latest version.
The last upload time is also incorrect, as nothing has ever been uploaded.

![main screenshot](https://github.com/user-attachments/assets/8685137a-35c7-47ce-87bc-cc88fc5e5d72)
![dahsboard screenshot 1](https://github.com/user-attachments/assets/0bc1e717-5826-4b6b-937e-245f4b99a277)
![dahsboard screenshot 2](https://github.com/user-attachments/assets/497b2042-b6cf-445b-962d-16569bd98e5f)
