### ISSUE TITLE
ALGUIEN SABE SI SIGUE FUNCIONANDO !?

### ISSUE THREAD

**Issue by Tenseotakeover** [sujay1599/InstagramTheftyScraperPosterHuman#9]
He probado otros pero no me terminaban de funcionar, y vi el comentario del dueño de este repositorio diciendo que descargásemos el suyo y querría saber si alguien lo sigue utilizando a día de hoy o dejo de funcionar o algo, muchas gracias de antemano.

**Comment by sujay1599** [comment]
should work;; will update in 24 there has been repository changes from source!

**Comment by sujay1599** [comment]
merged
